### ISSUE TITLE
Trouble Compiling

### ISSUE THREAD

**Issue by rob-gordon** [Xavura/CoffeeScript-Sublime-Plugin#49]
I get this error when trying to Build. I'm not sure if building is equivalent to compiling for this plug-in. Does anyone have any suggestions?

    /usr/local/lib/node_modules/coffee-script/lib/coffee-script/cake.js:111
    throw new Error("Cakefile not found in " + (process.cwd()));
          ^
    Error: Cakefile not found in /Users/robgordon/Music/Max/skewDrum
    at cakefileDirectory (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/cake.js:111:11)
    at cakefileDirectory (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/cake.js:109:14)
    at cakefileDirectory (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/cake.js:109:14)
    at cakefileDirectory (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/cake.js:109:14)
    at cakefileDirectory (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/cake.js:109:14)
    at cakefileDirectory (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/cake.js:109:14)
    at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/cake.js:51:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/cake:7:38)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
    [Finished in 0.2s with exit code 1]

**Comment by transfluxus** [comment]
where can I find this file on osx?

**Comment by grittymindy** [comment]
@nachocab it works.
